### ISSUE TITLE
Parenthesis and underscore doesn't work?

### ISSUE THREAD

**Issue by mathmathniconico** [AaronCQL/katex-github-chrome-extension#1]
Hi, this is an extension that I wanted, awesome.

I tested this in my notes and it works here: ( sorry for Japanese text )
https://github.com/mathmathniconico/Notes/blob/master/Manifold/Tangent.md

but it **doesn't** work here:
https://github.com/mathmathniconico/Notes/blob/master/ConvergentSpace/Conv.md

So, I think the problem is not just underscore, but '}_' or something.

I hope you will fix this problem, thank you.

**Comment by AaronCQL** [comment]
Hey @mathmathniconico, thanks for the bug report. This is actually a [known issue](https://github.com/AaronCQL/katex-github-chrome-extension#subscripts-using-_-may-not-render-correctly) and is due to GitHub's inbuilt Markdown parser. This extension works by parsing the resulting DOM *after* GitHub has parsed the Markdown and transformed it into HTML. Since the `_` character is used as a delimiter for italic text, and since the `$` character is not recognised as a delimiter by GitHub, GitHub's parser will parse the `_` inside the math blocks and transform them into `<em>` tags. As you have noticed, this occurs when the `_` character proceeds the `}` character (which is when GitHub decides to parse it as a `<em>` tag).

Potential fixes include:

1. Get the raw markdown source file and totally replace GitHub's Markdown preview implementation
2. Remove all `<em>` tags in the parsed DOM (before parsing the math)
3. Detect all math blocks, and remove any `<em>` tags in them in the parsed DOM (before parsing the math)

Option 1 is the cleanest solution, but is not suitable as it will not work with private repositories (unless provided with access). Option 2 may be the easiest, but is equally undesirable since it has the potential to remove some `<em>` tags not in the math blocks. Option 3 requires more work and testing (not sure if there will be undesirable effects), but seems to be the best solution so far and will be the one that I will try to work on.

Do let me know if you have any suggestions.
